/*
 * 7346a0 IRQ header file autogenerated by update_bchp.pl
 * DO NOT EDIT THIS FILE BY HAND.
 *
 * Copyright (C) 2010 Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef _BRCMIRQ_H_
#define _BRCMIRQ_H_

#define BRCM_IRQ_EHCI0_0	63
#define BRCM_IRQ_EHCI0_1	64
#define BRCM_IRQ_EHCI1_0	77
#define BRCM_IRQ_EHCI1_1	78
#define BRCM_IRQ_GENET_0_A	16
#define BRCM_IRQ_GENET_0_B	70
#define BRCM_IRQ_GENET_1_A	56
#define BRCM_IRQ_GENET_1_B	57
#define BRCM_IRQ_HIF		1
#define BRCM_IRQ_HIF_SPI	17
#define BRCM_IRQ_MOCA		69
#define BRCM_IRQ_OHCI0_0	65
#define BRCM_IRQ_OHCI0_1	60
#define BRCM_IRQ_OHCI1_0	79
#define BRCM_IRQ_OHCI1_1	76
#define BRCM_IRQ_UARTA		22
#define BRCM_IRQ_UARTB		67
#define BRCM_IRQ_UARTC		68
#define BRCM_IRQ_UPG		19

#endif /* _BRCMIRQ_H_ */
