/*
 * 7135a0 IRQ header file autogenerated by update_bchp.pl
 * DO NOT EDIT THIS FILE BY HAND.
 *
 * Copyright (C) 2010 Broadcom Corporation
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef _BRCMIRQ_H_
#define _BRCMIRQ_H_

#define BRCM_IRQ_EHCI0_0	56
#define BRCM_IRQ_GENET_0_A	28
#define BRCM_IRQ_GENET_0_B	29
#define BRCM_IRQ_HIF		32
#define BRCM_IRQ_HIF_SPI	33
#define BRCM_IRQ_MOCA		38
#define BRCM_IRQ_OHCI0_0	57
#define BRCM_IRQ_UARTA		52
#define BRCM_IRQ_UARTB		53
#define BRCM_IRQ_UARTC		54
#define BRCM_IRQ_UPG		46

#endif /* _BRCMIRQ_H_ */
